/**
 * Venue Service
 * Service for fetching and filtering venues and specials
 */

import { Venue, VenueListItem, VenueFilters, AdvancedVenueFilters, Special } from '../types/venue.types';
import RecommendationService from './RecommendationService';

// Mock Venues Data - Realistic Australian Pubs & Bars
export const MOCK_VENUES: Venue[] = [
    {
        id: '1',
        name: 'The Baxter Inn',
        description: 'Hidden basement whisky bar with over 800 whiskies. Intimate speakeasy vibes with expert bartenders.',
        address: '152-156 Clarence St, Sydney',
        suburb: 'Sydney CBD',
        city: 'Sydney',
        postcode: '2000',
        latitude: -33.8688,
        longitude: 151.2063,
        phone: '02 9264 4949',
        email: 'hello@thebaxterinn.com',
        imageUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=800&q=80',
        images: [],
        rating: 4.5,
        reviewCount: 2847,
        categories: ['Whisky Bar', 'Cocktail Bar'],
        specialsCount: 4,
        isInsiderPick: true,
        isFavorite: false,
        operatingHours: {
            monday: { open: '16:00', close: '01:00', isClosed: false },
            tuesday: { open: '16:00', close: '01:00', isClosed: false },
            wednesday: { open: '16:00', close: '01:00', isClosed: false },
            thursday: { open: '16:00', close: '01:00', isClosed: false },
            friday: { open: '16:00', close: '01:00', isClosed: false },
            saturday: { open: '16:00', close: '01:00', isClosed: false },
            sunday: { open: '00:00', close: '00:00', isClosed: true },
        },
        priceRange: '$$$',
        createdAt: new Date('2023-01-01'),
        updatedAt: new Date(),
    },
    {
        id: '2',
        name: 'The Glenmore Hotel',
        description: 'Historic Rocks pub with stunning 180-degree views of Sydney Harbour. Perfect for sunset drinks.',
        address: '96 Cumberland St, The Rocks',
        suburb: 'The Rocks',
        city: 'Sydney',
        postcode: '2000',
        latitude: -33.8598,
        longitude: 151.2063,
        phone: '02 9247 4714',
        email: 'info@theglenmore.com.au',
        imageUrl: 'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?auto=format&fit=crop&w=800&q=80',
        images: [],
        rating: 4.3,
        reviewCount: 1842,
        categories: ['Pub', 'Rooftop Bar'],
        specialsCount: 3,
        isInsiderPick: true,
        isFavorite: false,
        operatingHours: {
            monday: { open: '11:00', close: '00:00', isClosed: false },
            tuesday: { open: '11:00', close: '00:00', isClosed: false },
            wednesday: { open: '11:00', close: '00:00', isClosed: false },
            thursday: { open: '11:00', close: '00:00', isClosed: false },
            friday: { open: '11:00', close: '01:00', isClosed: false },
            saturday: { open: '11:00', close: '01:00', isClosed: false },
            sunday: { open: '11:00', close: '00:00', isClosed: false },
        },
        priceRange: '$$',
        createdAt: new Date('2022-12-01'),
        updatedAt: new Date(),
    },
    {
        id: '3',
        name: 'Frankie\'s Pizza',
        description: 'Rock \'n\' roll pizza joint with live music downstairs. NYC-style slices and craft beers.',
        address: '50 Hunter St, Sydney',
        suburb: 'Sydney CBD',
        city: 'Sydney',
        postcode: '2000',
        latitude: -33.8658,
        longitude: 151.2093,
        phone: '02 9114 7722',
        email: 'hello@frankiespizzabytheslice.com',
        imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
        images: [],
        rating: 3.9,
        reviewCount: 3156,
        categories: ['Bar', 'Live Music', 'Pizza'],
        specialsCount: 5,
        isInsiderPick: false,
        isFavorite: false,
        operatingHours: {
            monday: { open: '12:00', close: '03:00', isClosed: false },
            tuesday: { open: '12:00', close: '03:00', isClosed: false },
            wednesday: { open: '12:00', close: '03:00', isClosed: false },
            thursday: { open: '12:00', close: '03:00', isClosed: false },
            friday: { open: '12:00', close: '03:00', isClosed: false },
            saturday: { open: '12:00', close: '03:00', isClosed: false },
            sunday: { open: '12:00', close: '03:00', isClosed: false },
        },
        priceRange: '$',
        createdAt: new Date('2023-02-15'),
        updatedAt: new Date(),
    },
    {
        id: '4',
        name: 'The Winery',
        description: 'Surry Hills wine bar with 400+ wines by the glass. Seasonal small plates and cheese boards.',
        address: '285A Crown St, Surry Hills',
        suburb: 'Surry Hills',
        city: 'Sydney',
        postcode: '2010',
        latitude: -33.8838,
        longitude: 151.2133,
        phone: '02 9331 5999',
        email: 'info@thewinery.com.au',
        imageUrl: 'https://images.unsplash.com/photo-1550966842-30c29a4a229f?auto=format&fit=crop&w=800&q=80',
        images: [],
        rating: 4.4,
        reviewCount: 892,
        categories: ['Wine Bar', 'Restaurant'],
        specialsCount: 2,
        isInsiderPick: true,
        isFavorite: false,
        operatingHours: {
            monday: { open: '00:00', close: '00:00', isClosed: true },
            tuesday: { open: '17:00', close: '23:00', isClosed: false },
            wednesday: { open: '17:00', close: '23:00', isClosed: false },
            thursday: { open: '17:00', close: '23:00', isClosed: false },
            friday: { open: '17:00', close: '00:00', isClosed: false },
            saturday: { open: '12:00', close: '00:00', isClosed: false },
            sunday: { open: '12:00', close: '22:00', isClosed: false },
        },
        priceRange: '$$$',
        createdAt: new Date('2023-03-20'),
        updatedAt: new Date(),
    },
    {
        id: '5',
        name: 'The Lord Nelson Brewery Hotel',
        description: 'Australia\'s oldest continually licensed pub (1841). Craft brewery with heritage charm.',
        address: '19 Kent St, The Rocks',
        suburb: 'The Rocks',
        city: 'Sydney',
        postcode: '2000',
        latitude: -33.8578,
        longitude: 151.2053,
        phone: '02 9251 4044',
        email: 'info@lordnelsonbrewery.com',
        imageUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=800&q=80',
        images: [],
        rating: 4.2,
        reviewCount: 1567,
        categories: ['Pub', 'Brewery', 'Restaurant'],
        specialsCount: 4,
        isInsiderPick: true,
        isFavorite: false,
        operatingHours: {
            monday: { open: '12:00', close: '22:00', isClosed: false },
            tuesday: { open: '12:00', close: '22:00', isClosed: false },
            wednesday: { open: '12:00', close: '22:00', isClosed: false },
            thursday: { open: '12:00', close: '23:00', isClosed: false },
            friday: { open: '12:00', close: '00:00', isClosed: false },
            saturday: { open: '12:00', close: '00:00', isClosed: false },
            sunday: { open: '12:00', close: '22:00', isClosed: false },
        },
        priceRange: '$$',
        createdAt: new Date('2022-11-10'),
        updatedAt: new Date(),
    },
    {
        id: '6',
        name: 'Maybe Sammy',
        description: 'Award-winning cocktail bar with theatrical presentations. Reservations essential.',
        address: '23 Lime St, Sydney',
        suburb: 'Sydney CBD',
        city: 'Sydney',
        postcode: '2000',
        latitude: -33.8668,
        longitude: 151.2073,
        phone: '02 8964 5945',
        email: 'hello@maybesammy.com',
        imageUrl: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&w=800&q=80',
        images: [],
        rating: 4.6,
        reviewCount: 743,
        categories: ['Cocktail Bar'],
        specialsCount: 0,
        isInsiderPick: true,
        isFavorite: false,
        operatingHours: {
            monday: { open: '00:00', close: '00:00', isClosed: true },
            tuesday: { open: '00:00', close: '00:00', isClosed: true },
            wednesday: { open: '17:00', close: '00:00', isClosed: false },
            thursday: { open: '17:00', close: '00:00', isClosed: false },
            friday: { open: '17:00', close: '01:00', isClosed: false },
            saturday: { open: '17:00', close: '01:00', isClosed: false },
            sunday: { open: '00:00', close: '00:00', isClosed: true },
        },
        priceRange: '$$$$',
        createdAt: new Date('2023-04-05'),
        updatedAt: new Date(),
    },
    {
        id: '7',
        name: 'The Beresford Hotel',
        description: 'Surry Hills institution with rooftop bar, live music, and classic pub fare.',
        address: '354 Bourke St, Surry Hills',
        suburb: 'Surry Hills',
        city: 'Sydney',
        postcode: '2010',
        latitude: -33.8888,
        longitude: 151.2123,
        phone: '02 9357 1111',
        email: 'info@beresfordhotel.com.au',
        imageUrl: 'https://images.unsplash.com/photo-1533900298318-6b8da08a523e?auto=format&fit=crop&w=800&q=80',
        images: [],
        rating: 3.8,
        reviewCount: 2134,
        categories: ['Pub', 'Live Music', 'Rooftop Bar', 'Beer Garden', 'Pool Tables'],
        specialsCount: 6,
        isInsiderPick: false,
        isFavorite: false,
        operatingHours: {
            monday: { open: '12:00', close: '00:00', isClosed: false },
            tuesday: { open: '12:00', close: '00:00', isClosed: false },
            wednesday: { open: '12:00', close: '00:00', isClosed: false },
            thursday: { open: '12:00', close: '02:00', isClosed: false },
            friday: { open: '12:00', close: '03:00', isClosed: false },
            saturday: { open: '12:00', close: '03:00', isClosed: false },
            sunday: { open: '12:00', close: '00:00', isClosed: false },
        },
        priceRange: '$$',
        createdAt: new Date('2023-01-25'),
        updatedAt: new Date(),
    },
    {
        id: '8',
        name: 'The Doss House',
        description: 'Cozy wine bar in Surry Hills. Natural wines, craft beers, and seasonal snacks.',
        address: '77-79 Liverpool St, Sydney',
        suburb: 'Surry Hills',
        city: 'Sydney',
        postcode: '2010',
        latitude: -33.8808,
        longitude: 151.2113,
        phone: '02 9211 4958',
        email: 'info@thedosshouse.com.au',
        imageUrl: 'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?auto=format&fit=crop&w=800&q=80',
        images: [],
        rating: 4.1,
        reviewCount: 456,
        categories: ['Wine Bar', 'Bar'],
        specialsCount: 3,
        isInsiderPick: false,
        isFavorite: false,
        operatingHours: {
            monday: { open: '00:00', close: '00:00', isClosed: true },
            tuesday: { open: '17:00', close: '00:00', isClosed: false },
            wednesday: { open: '17:00', close: '00:00', isClosed: false },
            thursday: { open: '17:00', close: '00:00', isClosed: false },
            friday: { open: '17:00', close: '01:00', isClosed: false },
            saturday: { open: '17:00', close: '01:00', isClosed: false },
            sunday: { open: '17:00', close: '00:00', isClosed: false },
        },
        priceRange: '$$',
        createdAt: new Date('2023-02-28'),
        updatedAt: new Date(),
    },

    {
        id: '12',
        name: 'Young Henrys Newtown',
        description: 'Craft brewery and taproom. Fresh beers brewed on-site with rotating food trucks.',
        address: '76 Wilford St, Newtown',
        suburb: 'Newtown',
        city: 'Sydney',
        postcode: '2042',
        latitude: -33.8978,
        longitude: 151.1803,
        phone: '02 9519 0048',
        email: 'hello@younghenrys.com',
        imageUrl: 'https://images.unsplash.com/photo-1532634922-8fe0b757fb13?auto=format&fit=crop&w=800&q=80',
        images: [],
        rating: 4.3,
        reviewCount: 1678,
        categories: ['Brewery', 'Bar'],
        specialsCount: 5,
        isInsiderPick: true,
        isFavorite: false,
        operatingHours: {
            monday: { open: '00:00', close: '00:00', isClosed: true },
            tuesday: { open: '00:00', close: '00:00', isClosed: true },
            wednesday: { open: '15:00', close: '22:00', isClosed: false },
            thursday: { open: '15:00', close: '22:00', isClosed: false },
            friday: { open: '12:00', close: '23:00', isClosed: false },
            saturday: { open: '12:00', close: '23:00', isClosed: false },
            sunday: { open: '12:00', close: '20:00', isClosed: false },
        },
        priceRange: '$$',
        createdAt: new Date('2023-02-05'),
        updatedAt: new Date(),
    },
    {
        id: '13',
        name: 'The Royal Oak',
        description: 'Classic sports pub in Double Bay. Famous for its pool tables, live sports screens, and great pub grub.',
        address: '28 Bay St, Double Bay',
        suburb: 'Double Bay',
        city: 'Sydney',
        postcode: '2028',
        latitude: -33.8768,
        longitude: 151.2423,
        phone: '02 9363 3935',
        email: 'info@royaloakdoublebay.com.au',
        imageUrl: 'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?auto=format&fit=crop&w=800&q=80',
        images: [],
        rating: 3.9,
        reviewCount: 982,
        categories: ['Pub', 'Sports Bar', 'Pool Tables', 'Restaurant'],
        specialsCount: 4,
        isInsiderPick: false,
        isFavorite: false,
        operatingHours: {
            monday: { open: '10:00', close: '00:00', isClosed: false },
            tuesday: { open: '10:00', close: '00:00', isClosed: false },
            wednesday: { open: '10:00', close: '00:00', isClosed: false },
            thursday: { open: '10:00', close: '00:00', isClosed: false },
            friday: { open: '10:00', close: '01:00', isClosed: false },
            saturday: { open: '10:00', close: '01:00', isClosed: false },
            sunday: { open: '10:00', close: '23:00', isClosed: false },
        },
        priceRange: '$$',
        createdAt: new Date('2023-01-10'),
        updatedAt: new Date(),
    },
    {
        id: '15',
        name: 'City Heroes Pool & Billiards',
        description: 'Sydney\'s premier pool hall located below Event Cinemas. Features dozens of tables and arcade games.',
        address: '505 George St, Sydney',
        suburb: 'Sydney CBD',
        city: 'Sydney',
        postcode: '2000',
        latitude: -33.8749,
        longitude: 151.2069,
        phone: '02 9267 3388',
        email: 'info@cityheroes.com.au',
        imageUrl: 'https://images.unsplash.com/photo-1577563908411-5077b6dc7624?auto=format&fit=crop&w=800&q=80',
        images: [],
        rating: 4.2,
        reviewCount: 3241,
        categories: ['Pool Tables', 'Arcade', 'Bar'],
        specialsCount: 2,
        isInsiderPick: true,
        isFavorite: false,
        operatingHours: {
            monday: { open: '10:00', close: '02:00', isClosed: false },
            tuesday: { open: '10:00', close: '02:00', isClosed: false },
            wednesday: { open: '10:00', close: '02:00', isClosed: false },
            thursday: { open: '10:00', close: '03:00', isClosed: false },
            friday: { open: '10:00', close: '04:00', isClosed: false },
            saturday: { open: '10:00', close: '04:00', isClosed: false },
            sunday: { open: '10:00', close: '02:00', isClosed: false },
        },
        priceRange: '$',
        createdAt: new Date('2023-05-01'),
        updatedAt: new Date(),
    },
    {
        id: '16',
        name: 'Shark Hotel',
        description: 'Spacious venue with plenty of pool tables, Thai food, and affordable drinks.',
        address: '127 Liverpool St, Sydney',
        suburb: 'Sydney CBD',
        city: 'Sydney',
        postcode: '2000',
        latitude: -33.8778,
        longitude: 151.2093,
        phone: '02 9267 7888',
        email: 'info@sharkhotel.com.au',
        imageUrl: 'https://images.unsplash.com/photo-1517604931442-71053e3e2e3c?auto=format&fit=crop&w=800&q=80',
        images: [],
        rating: 4.0,
        reviewCount: 1543,
        categories: ['Pool Tables', 'Pub', 'Thai'],
        specialsCount: 3,
        isInsiderPick: false,
        isFavorite: false,
        operatingHours: {
            monday: { open: '10:00', close: '04:00', isClosed: false },
            tuesday: { open: '10:00', close: '04:00', isClosed: false },
            wednesday: { open: '10:00', close: '04:00', isClosed: false },
            thursday: { open: '10:00', close: '04:00', isClosed: false },
            friday: { open: '10:00', close: '06:00', isClosed: false },
            saturday: { open: '10:00', close: '06:00', isClosed: false },
            sunday: { open: '10:00', close: '04:00', isClosed: false },
        },
        priceRange: '$',
        createdAt: new Date('2023-05-02'),
        updatedAt: new Date(),
    },
    // --- North Sydney ---
    {
        id: '17',
        phone: '02 9964 9477',
        email: 'info@greenwood.com.au',
        name: 'The Greenwood Hotel',
        description: 'Iconic North Sydney pub in a converted schoolhouse. Huge courtyard, perfect for Friday drinks.',
        address: '36 Blue St, North Sydney',
        suburb: 'North Sydney',
        city: 'Sydney',
        postcode: '2060',
        latitude: -33.8404,
        longitude: 151.2078,

        imageUrl: 'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800&q=80',
        rating: 4.1,
        categories: ['Pub', 'Beer Garden', 'Live Music'],
        specialsCount: 3,
        isInsiderPick: false, isFavorite: false, images: [], reviewCount: 890,
        createdAt: new Date(), updatedAt: new Date(),
        priceRange: '$$', operatingHours: { monday: { open: '11:00', close: '00:00', isClosed: false }, tuesday: { open: '11:00', close: '00:00', isClosed: false }, wednesday: { open: '11:00', close: '00:00', isClosed: false }, thursday: { open: '11:00', close: '00:00', isClosed: false }, friday: { open: '11:00', close: '00:00', isClosed: false }, saturday: { open: '12:00', close: '00:00', isClosed: false }, sunday: { open: '12:00', close: '22:00', isClosed: false } }
    },
    {
        id: '18',
        phone: '02 9955 1257',
        email: 'info@ragandfamish.com.au',
        name: 'Rag & Famish',
        description: 'North Sydney\'s oldest pub. Traditional vibes, great pies, and a cozy courtyard.',
        address: '199 Miller St, North Sydney',
        suburb: 'North Sydney',
        city: 'Sydney',
        postcode: '2060',
        latitude: -33.8368,
        longitude: 151.2065,
        rating: 4.3,
        categories: ['Pub', 'Food'],
        specialsCount: 2,
        imageUrl: 'https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=800&q=80',
        isInsiderPick: true, isFavorite: false, images: [], reviewCount: 450,
        createdAt: new Date(), updatedAt: new Date(),
        priceRange: '$$', operatingHours: { monday: { open: '11:00', close: '23:00', isClosed: false }, tuesday: { open: '11:00', close: '23:00', isClosed: false }, wednesday: { open: '11:00', close: '00:00', isClosed: false }, thursday: { open: '11:00', close: '00:00', isClosed: false }, friday: { open: '11:00', close: '00:00', isClosed: false }, saturday: { open: '12:00', close: '00:00', isClosed: false }, sunday: { open: '12:00', close: '22:00', isClosed: false } }
    },
    {
        id: '19',
        phone: '02 8458 8980',
        email: 'info@treehouse.com.au',
        name: 'Treehouse Hotel',
        description: 'Trendy bar with vibrant decor, serving cocktails and modern Australian food.',
        address: '60 Miller St, North Sydney',
        suburb: 'North Sydney',
        city: 'Sydney',
        postcode: '2060',
        latitude: -33.8430,
        longitude: 151.2081,
        rating: 4.0,
        categories: ['Bar', 'Restaurant', 'Cocktail Bar'],
        specialsCount: 1,
        imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&q=80',
        isInsiderPick: false, isFavorite: false, images: [], reviewCount: 320,
        createdAt: new Date(), updatedAt: new Date(),
        priceRange: '$$$', operatingHours: { monday: { open: '07:30', close: '23:00', isClosed: false }, tuesday: { open: '07:30', close: '23:00', isClosed: false }, wednesday: { open: '07:30', close: '00:00', isClosed: false }, thursday: { open: '07:30', close: '00:00', isClosed: false }, friday: { open: '07:30', close: '00:00', isClosed: false }, saturday: { open: '16:00', close: '00:00', isClosed: false }, sunday: { open: '00:00', close: '00:00', isClosed: true } }
    },
    // --- Sydney CBD / Rocks ---
    {
        id: '20',
        phone: '02 9251 1255',
        email: 'info@orienthotel.com.au',
        name: 'The Orient Hotel',
        description: 'Historic Rocks pub with live bands and a lively outdoor seating area.',
        address: '89 George St, The Rocks',
        suburb: 'The Rocks',
        city: 'Sydney',
        postcode: '2000',
        latitude: -33.8584,
        longitude: 151.2078,
        rating: 3.9,
        categories: ['Pub', 'Live Music'],
        specialsCount: 0,
        imageUrl: 'https://images.unsplash.com/photo-1583852109961-a548c77227ac?w=800&q=80',
        isInsiderPick: false, isFavorite: false, images: [], reviewCount: 1200,
        createdAt: new Date(), updatedAt: new Date(),
        priceRange: '$$', operatingHours: { monday: { open: '11:00', close: '00:00', isClosed: false }, tuesday: { open: '11:00', close: '00:00', isClosed: false }, wednesday: { open: '11:00', close: '01:00', isClosed: false }, thursday: { open: '11:00', close: '01:00', isClosed: false }, friday: { open: '11:00', close: '02:00', isClosed: false }, saturday: { open: '11:00', close: '02:00', isClosed: false }, sunday: { open: '11:00', close: '00:00', isClosed: false } }
    },
    {
        id: '21',
        phone: '02 9114 7315',
        email: 'hello@palmerandco.com.au',
        name: 'Palmer & Co',
        description: 'Prohibition-style speakeasy underground. Dapper staff and classic cocktails.',
        address: 'Abercrombie Lane, Sydney',
        suburb: 'Sydney CBD',
        city: 'Sydney',
        postcode: '2000',
        latitude: -33.8645,
        longitude: 151.2084,
        rating: 4.6,
        categories: ['Cocktail Bar', 'Bar', 'Live Music'],
        specialsCount: 0,
        imageUrl: 'https://images.unsplash.com/photo-1542125211-18c7c936056b?w=800&q=80',
        isInsiderPick: true, isFavorite: false, images: [], reviewCount: 980,
        createdAt: new Date(), updatedAt: new Date(),
        priceRange: '$$$', operatingHours: { monday: { open: '00:00', close: '00:00', isClosed: true }, tuesday: { open: '17:00', close: '01:00', isClosed: false }, wednesday: { open: '17:00', close: '01:00', isClosed: false }, thursday: { open: '17:00', close: '02:00', isClosed: false }, friday: { open: '16:00', close: '03:00', isClosed: false }, saturday: { open: '16:00', close: '03:00', isClosed: false }, sunday: { open: '17:00', close: '00:00', isClosed: false } }
    },
    {
        id: '22',
        phone: '02 9262 7210',
        email: 'info@cheersbar.com.au',
        name: 'Cheers Bar',
        description: 'Popular sports bar open late. 24-hour license on weekends. Great for EPL.',
        address: '561 George St, Sydney',
        suburb: 'Sydney CBD',
        city: 'Sydney',
        postcode: '2000',
        latitude: -33.8761,
        longitude: 151.2066,
        rating: 3.8,
        categories: ['Sports Bar', 'Pub', 'Pool Tables'],
        specialsCount: 4,
        imageUrl: 'https://images.unsplash.com/photo-1575024095493-27a3f5f8484a?w=800&q=80',
        isInsiderPick: false, isFavorite: false, images: [], reviewCount: 560,
        createdAt: new Date(), updatedAt: new Date(),
        priceRange: '$', operatingHours: { monday: { open: '09:00', close: '04:00', isClosed: false }, tuesday: { open: '09:00', close: '04:00', isClosed: false }, wednesday: { open: '09:00', close: '04:00', isClosed: false }, thursday: { open: '09:00', close: '05:00', isClosed: false }, friday: { open: '09:00', close: '06:00', isClosed: false }, saturday: { open: '09:00', close: '06:00', isClosed: false }, sunday: { open: '09:00', close: '04:00', isClosed: false } }
    },
    // --- Paddington ---
    {
        id: '23',
        phone: '02 9380 5913',
        email: 'hello@paddingtoninn.com.au',
        name: 'The Paddington Inn',
        description: 'Stylish gastropub on Oxford St. Great food and front bar action.',
        address: '338 Oxford St, Paddington',
        suburb: 'Paddington',
        city: 'Sydney',
        postcode: '2021',
        latitude: -33.8864,
        longitude: 151.2291,
        rating: 4.2,
        categories: ['Pub', 'Restaurant'],
        specialsCount: 2,
        imageUrl: 'https://images.unsplash.com/photo-1560624052-449f5ddf0c31?w=800&q=80',
        isInsiderPick: false, isFavorite: false, images: [], reviewCount: 410,
        createdAt: new Date(), updatedAt: new Date(),
        priceRange: '$$$', operatingHours: { monday: { open: '12:00', close: '00:00', isClosed: false }, tuesday: { open: '12:00', close: '00:00', isClosed: false }, wednesday: { open: '12:00', close: '00:00', isClosed: false }, thursday: { open: '12:00', close: '00:00', isClosed: false }, friday: { open: '12:00', close: '01:00', isClosed: false }, saturday: { open: '12:00', close: '01:00', isClosed: false }, sunday: { open: '12:00', close: '22:00', isClosed: false } }
    },
    {
        id: '24',
        phone: '02 9331 3200',
        email: 'info@hotellondon.com.au',
        name: 'The London Hotel',
        description: 'Corner pub beloved by locals. Good beers and watching the world go by.',
        address: '85 Underwood St, Paddington',
        suburb: 'Paddington',
        city: 'Sydney',
        postcode: '2021',
        latitude: -33.8858,
        longitude: 151.2268,
        rating: 4.1,
        categories: ['Pub'],
        specialsCount: 1,
        imageUrl: 'https://images.unsplash.com/photo-1570554868062-81822cb6cb10?w=800&q=80',
        isInsiderPick: false, isFavorite: false, images: [], reviewCount: 330,
        createdAt: new Date(), updatedAt: new Date(),
        priceRange: '$$', operatingHours: { monday: { open: '12:00', close: '00:00', isClosed: false }, tuesday: { open: '12:00', close: '00:00', isClosed: false }, wednesday: { open: '12:00', close: '00:00', isClosed: false }, thursday: { open: '12:00', close: '00:00', isClosed: false }, friday: { open: '12:00', close: '00:00', isClosed: false }, saturday: { open: '12:00', close: '00:00', isClosed: false }, sunday: { open: '12:00', close: '22:00', isClosed: false } }
    },
    {
        id: '25',
        phone: '02 9357 0888',
        email: 'hello@lightbrigade.com.au',
        name: 'The Light Brigade',
        description: 'Art Deco pub with a rooftop bar boasting city views.',
        address: '2 Oxford St, Woollahra',
        suburb: 'Paddington',
        city: 'Sydney',
        postcode: '2025',
        latitude: -33.8893,
        longitude: 151.2335,
        rating: 4.4,
        categories: ['Pub', 'Rooftop Bar'],
        specialsCount: 3,
        imageUrl: 'https://images.unsplash.com/photo-1582260429737-14736142d5c3?w=800&q=80',
        isInsiderPick: true, isFavorite: false, images: [], reviewCount: 670,
        createdAt: new Date(), updatedAt: new Date(),
        priceRange: '$$', operatingHours: { monday: { open: '12:00', close: '00:00', isClosed: false }, tuesday: { open: '12:00', close: '00:00', isClosed: false }, wednesday: { open: '12:00', close: '00:00', isClosed: false }, thursday: { open: '12:00', close: '01:00', isClosed: false }, friday: { open: '12:00', close: '01:00', isClosed: false }, saturday: { open: '10:00', close: '01:00', isClosed: false }, sunday: { open: '12:00', close: '22:00', isClosed: false } }
    },
    // --- Bondi ---
    {
        id: '26',
        phone: '02 9130 3120',
        email: 'info@icebergs.com.au',
        name: 'Bondi Icebergs Club',
        description: 'World-famous club overlooking the ocean pool. Bistro food and cold drinks with a view.',
        address: '1 Notts Ave, Bondi Beach',
        suburb: 'Bondi Beach',
        city: 'Sydney',
        postcode: '2026',
        latitude: -33.8966,
        longitude: 151.2748,
        rating: 4.7,
        categories: ['Bar', 'Restaurant', 'Club'],
        specialsCount: 1,
        imageUrl: 'https://images.unsplash.com/photo-1578474846511-04ba529f0b88?w=800&q=80',
        isInsiderPick: true, isFavorite: false, images: [], reviewCount: 2200,
        createdAt: new Date(), updatedAt: new Date(),
        priceRange: '$$', operatingHours: { monday: { open: '11:00', close: '22:00', isClosed: false }, tuesday: { open: '11:00', close: '22:00', isClosed: false }, wednesday: { open: '11:00', close: '22:00', isClosed: false }, thursday: { open: '11:00', close: '22:00', isClosed: false }, friday: { open: '11:00', close: '22:00', isClosed: false }, saturday: { open: '10:00', close: '22:00', isClosed: false }, sunday: { open: '10:00', close: '22:00', isClosed: false } }
    },
    {
        id: '27',
        phone: '02 9365 4422',
        email: 'info@hotelravesis.com.au',
        name: 'Hotel Ravesis',
        description: 'Pastel-hued beachside hotel. Ideal for post-swim drinks and people watching.',
        address: '118 Campbell Parade, Bondi Beach',
        suburb: 'Bondi Beach',
        city: 'Sydney',
        postcode: '2026',
        latitude: -33.8926,
        longitude: 151.2736,
        rating: 4.0,
        categories: ['Pub', 'Bar'],
        specialsCount: 2,
        imageUrl: 'https://images.unsplash.com/photo-1525283584841-35b89793175c?w=800&q=80',
        isInsiderPick: false, isFavorite: false, images: [], reviewCount: 890,
        createdAt: new Date(), updatedAt: new Date(),
        priceRange: '$$$', operatingHours: { monday: { open: '12:00', close: '00:00', isClosed: false }, tuesday: { open: '12:00', close: '00:00', isClosed: false }, wednesday: { open: '12:00', close: '00:00', isClosed: false }, thursday: { open: '12:00', close: '00:00', isClosed: false }, friday: { open: '12:00', close: '01:00', isClosed: false }, saturday: { open: '10:00', close: '01:00', isClosed: false }, sunday: { open: '10:00', close: '22:00', isClosed: false } }
    },
    {
        id: '28',
        phone: '02 9130 7247',
        email: 'info@beachroadbondi.com.au',
        name: 'The Beach Road Hotel',
        description: 'Massive venue known for live music (Wednesday) and a relaxed beer garden.',
        address: '71 Beach Rd, Bondi Beach',
        suburb: 'Bondi Beach',
        city: 'Sydney',
        postcode: '2026',
        latitude: -33.8899,
        longitude: 151.2720,
        rating: 3.9,
        categories: ['Pub', 'Live Music', 'Pool Tables', 'Beer Garden'],
        specialsCount: 3,
        imageUrl: 'https://images.unsplash.com/photo-1542125211-18c7c936056b?w=800&q=80',
        isInsiderPick: false, isFavorite: false, images: [], reviewCount: 760,
        createdAt: new Date(), updatedAt: new Date(),
        priceRange: '$$', operatingHours: { monday: { open: '11:00', close: '01:00', isClosed: false }, tuesday: { open: '11:00', close: '01:00', isClosed: false }, wednesday: { open: '11:00', close: '01:00', isClosed: false }, thursday: { open: '11:00', close: '01:00', isClosed: false }, friday: { open: '11:00', close: '01:00', isClosed: false }, saturday: { open: '11:00', close: '01:00', isClosed: false }, sunday: { open: '11:00', close: '23:00', isClosed: false } }
    },
    // --- Rose Bay ---
    {
        id: '29',
        phone: '02 9371 9412',
        email: 'info@clubrosebay.com.au',
        name: 'Club Rose Bay',
        description: 'Local RSL club with harbour views and affordable drinks. Relaxed atmosphere.',
        address: '1 Vickery Ave, Rose Bay',
        suburb: 'Rose Bay',
        city: 'Sydney',
        postcode: '2029',
        latitude: -33.8710,
        longitude: 151.2660,
        rating: 3.8,
        categories: ['Club', 'Restaurant'],
        specialsCount: 1,
        imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80',
        isInsiderPick: false, isFavorite: false, images: [], reviewCount: 150,
        createdAt: new Date(), updatedAt: new Date(),
        priceRange: '$', operatingHours: { monday: { open: '12:00', close: '21:00', isClosed: false }, tuesday: { open: '12:00', close: '21:00', isClosed: false }, wednesday: { open: '12:00', close: '22:00', isClosed: false }, thursday: { open: '12:00', close: '22:00', isClosed: false }, friday: { open: '12:00', close: '23:00', isClosed: false }, saturday: { open: '11:00', close: '23:00', isClosed: false }, sunday: { open: '11:00', close: '21:00', isClosed: false } }
    },
    {
        id: '30',
        phone: '02 9327 5000',
        email: 'hello@hotelrosebay.com.au',
        name: 'Hotel Rose Bay',
        description: 'Refurbished pub (formerly Rose Bay Hotel). Modern, airy, and great food.',
        address: '807 New South Head Rd, Rose Bay',
        suburb: 'Rose Bay',
        city: 'Sydney',
        postcode: '2029',
        latitude: -33.8722,
        longitude: 151.2675,
        rating: 4.1,
        categories: ['Pub'],
        specialsCount: 2,
        imageUrl: 'https://images.unsplash.com/photo-1582260429737-14736142d5c3?w=800&q=80',
        isInsiderPick: false, isFavorite: false, images: [], reviewCount: 210,
        createdAt: new Date(), updatedAt: new Date(),
        priceRange: '$$', operatingHours: { monday: { open: '11:00', close: '23:00', isClosed: false }, tuesday: { open: '11:00', close: '23:00', isClosed: false }, wednesday: { open: '11:00', close: '23:00', isClosed: false }, thursday: { open: '11:00', close: '00:00', isClosed: false }, friday: { open: '11:00', close: '00:00', isClosed: false }, saturday: { open: '11:00', close: '00:00', isClosed: false }, sunday: { open: '12:00', close: '22:00', isClosed: false } }
    },
    // --- Surry Hills More ---
    {
        id: '31',
        phone: '02 9331 5333',
        email: 'info@clockhotel.com.au',
        name: 'The Clock Hotel',
        description: 'Surry Hills landmark with a balcony overlooking Crown St. A true locals favourite.',
        address: '470 Crown St, Surry Hills',
        suburb: 'Surry Hills',
        city: 'Sydney',
        postcode: '2010',
        latitude: -33.8867,
        longitude: 151.2144,
        rating: 4.3,
        categories: ['Pub', 'Bar'],
        specialsCount: 3,
        imageUrl: 'https://images.unsplash.com/photo-1549488344-cbb6c34cf08b?w=800&q=80',
        isInsiderPick: false, isFavorite: false, images: [], reviewCount: 1100,
        createdAt: new Date(), updatedAt: new Date(),
        priceRange: '$$', operatingHours: { monday: { open: '12:00', close: '00:00', isClosed: false }, tuesday: { open: '12:00', close: '00:00', isClosed: false }, wednesday: { open: '12:00', close: '00:00', isClosed: false }, thursday: { open: '12:00', close: '00:00', isClosed: false }, friday: { open: '12:00', close: '01:00', isClosed: false }, saturday: { open: '10:00', close: '01:00', isClosed: false }, sunday: { open: '10:00', close: '23:00', isClosed: false } }
    },
    {
        id: '32',
        phone: '02 9331 4800',
        email: 'info@dolphinhotel.com.au',
        name: 'The Dolphin Hotel',
        description: 'Chic, Keith Haring-esque interiors. Excellent pizza and wine list.',
        address: '412 Crown St, Surry Hills',
        suburb: 'Surry Hills',
        city: 'Sydney',
        postcode: '2010',
        latitude: -33.8851,
        longitude: 151.2141,
        rating: 4.2,
        categories: ['Pub', 'Restaurant', 'Wine Bar'],
        specialsCount: 0,
        imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80',
        isInsiderPick: false, isFavorite: false, images: [], reviewCount: 540,
        createdAt: new Date(), updatedAt: new Date(),
        priceRange: '$$$', operatingHours: { monday: { open: '12:00', close: '00:00', isClosed: false }, tuesday: { open: '12:00', close: '00:00', isClosed: false }, wednesday: { open: '12:00', close: '00:00', isClosed: false }, thursday: { open: '12:00', close: '00:00', isClosed: false }, friday: { open: '12:00', close: '00:00', isClosed: false }, saturday: { open: '12:00', close: '00:00', isClosed: false }, sunday: { open: '12:00', close: '22:00', isClosed: false } }
    },
    {
        id: '33',
        phone: '02 9211 4945',
        email: 'elloco@merivale.com',
        name: 'El Loco at Excelsior',
        description: 'Vibrant Mexican cantina in a pub setting. Tacos, margaritas, and loud music.',
        address: '64 Foveaux St, Surry Hills',
        suburb: 'Surry Hills',
        city: 'Sydney',
        postcode: '2010',
        latitude: -33.8842,
        longitude: 151.2096,
        rating: 4.1,
        categories: ['Pub', 'Restaurant'],
        specialsCount: 2,
        imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80',
        isInsiderPick: false, isFavorite: false, images: [], reviewCount: 680,
        createdAt: new Date(), updatedAt: new Date(),
        priceRange: '$$', operatingHours: { monday: { open: '12:00', close: '00:00', isClosed: false }, tuesday: { open: '12:00', close: '00:00', isClosed: false }, wednesday: { open: '12:00', close: '00:00', isClosed: false }, thursday: { open: '12:00', close: '01:00', isClosed: false }, friday: { open: '12:00', close: '03:00', isClosed: false }, saturday: { open: '12:00', close: '03:00', isClosed: false }, sunday: { open: '12:00', close: '00:00', isClosed: false } }
    },
    // --- Redfern ---
    {
        id: '34',
        phone: '02 9699 9888',
        email: 'love@thebeardedtit.com',
        name: 'The Bearded Tit',
        description: 'Quirky arts bar with eclectic decor and a creative vibe. A local favorite.',
        address: '183 Regent St, Redfern',
        suburb: 'Redfern',
        city: 'Sydney',
        postcode: '2016',
        latitude: -33.8924,
        longitude: 151.1993,
        rating: 4.5,
        categories: ['Bar', 'Art'],
        specialsCount: 0,
        imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&q=80',
        isInsiderPick: true, isFavorite: false, images: [], reviewCount: 430,
        createdAt: new Date(), updatedAt: new Date(),
        priceRange: '$$', operatingHours: { monday: { open: '16:00', close: '23:00', isClosed: false }, tuesday: { open: '16:00', close: '23:00', isClosed: false }, wednesday: { open: '16:00', close: '23:00', isClosed: false }, thursday: { open: '16:00', close: '00:00', isClosed: false }, friday: { open: '16:00', close: '00:00', isClosed: false }, saturday: { open: '14:00', close: '00:00', isClosed: false }, sunday: { open: '14:00', close: '22:00', isClosed: false } }
    },
    {
        id: '35',
        phone: '02 9318 1497',
        email: 'info@theredfern.com.au',
        name: 'The Redfern',
        description: 'Restored corner pub with a great Italian bistro upstairs. Classic public bar downstairs.',
        address: '106 George St, Redfern',
        suburb: 'Redfern',
        city: 'Sydney',
        postcode: '2016',
        latitude: -33.8930,
        longitude: 151.2005,
        rating: 4.0,
        categories: ['Pub', 'Restaurant'],
        specialsCount: 1,
        imageUrl: 'https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=800&q=80',
        isInsiderPick: false, isFavorite: false, images: [], reviewCount: 220,
        createdAt: new Date(), updatedAt: new Date(),
        priceRange: '$$', operatingHours: { monday: { open: '12:00', close: '00:00', isClosed: false }, tuesday: { open: '12:00', close: '00:00', isClosed: false }, wednesday: { open: '12:00', close: '00:00', isClosed: false }, thursday: { open: '12:00', close: '00:00', isClosed: false }, friday: { open: '12:00', close: '00:00', isClosed: false }, saturday: { open: '12:00', close: '00:00', isClosed: false }, sunday: { open: '12:00', close: '22:00', isClosed: false } }
    },
    {
        id: '36',
        phone: '02 9331 5333',
        email: 'hello@arcadialiquors.com',
        name: 'Arcadia Liquors',
        description: 'Intimate small bar with a leafy courtyard. Great sandwiches and craft beers.',
        address: '7 Cope St, Redfern',
        suburb: 'Redfern',
        city: 'Sydney',
        postcode: '2016',
        latitude: -33.8928,
        longitude: 151.2010,
        rating: 4.4,
        categories: ['Bar', 'Beer Garden'],
        specialsCount: 0,
        imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
        isInsiderPick: true, isFavorite: false, images: [], reviewCount: 380,
        createdAt: new Date(), updatedAt: new Date(),
        priceRange: '$$', operatingHours: { monday: { open: '16:00', close: '00:00', isClosed: false }, tuesday: { open: '16:00', close: '00:00', isClosed: false }, wednesday: { open: '16:00', close: '00:00', isClosed: false }, thursday: { open: '16:00', close: '00:00', isClosed: false }, friday: { open: '16:00', close: '00:00', isClosed: false }, saturday: { open: '16:00', close: '00:00', isClosed: false }, sunday: { open: '14:00', close: '22:00', isClosed: false } }

    }
];


class VenueService {
    /**
     * Fetch all venues with optional search and filters
     */
    async getVenues(filters?: VenueFilters, advancedFilters?: AdvancedVenueFilters): Promise<Venue[]> {
        // In a real app, this would be an API call
        let filtered = [...MOCK_VENUES];

        // Basic filters
        if (filters) {
            if (filters.searchQuery) {
                const query = filters.searchQuery.toLowerCase();
                filtered = filtered.filter(v =>
                    v.name.toLowerCase().includes(query) ||
                    v.suburb.toLowerCase().includes(query)
                );
            }

            if (filters.where && filters.where !== 'nearest') {
                filtered = filtered.filter(v =>
                    v.city.toLowerCase() === filters.where?.toLowerCase() ||
                    v.suburb.toLowerCase() === filters.where?.toLowerCase()
                );
            }

            if (filters.categories && filters.categories.length > 0) {
                filtered = filtered.filter(v =>
                    v.categories.some(c => filters.categories?.includes(c))
                );
            }
        }

        // Advanced filters
        if (advancedFilters) {
            if (advancedFilters.insiderPicksOnly) {
                filtered = filtered.filter(v => v.isInsiderPick);
            }

            if (advancedFilters.minRating) {
                filtered = filtered.filter(v => v.rating >= advancedFilters.minRating!);
            }

            if (advancedFilters.hasSpecials) {
                filtered = filtered.filter(v => v.specialsCount > 0);
            }
        }


        return filtered;
    }

    /**
     * Get venue by ID
     */
    async getVenueById(id: string): Promise<Venue | null> {
        return MOCK_VENUES.find(v => v.id === id) || null;
    }

    /**
     * Convert Venues to List Items for UI
     */
    toVenueListItems(venues: Venue[], favorites: string[] = []): VenueListItem[] {
        return venues.map(v => ({
            id: v.id,
            name: v.name,
            imageUrl: v.imageUrl,
            rating: v.rating,
            latitude: v.latitude,
            longitude: v.longitude,
            distance: v.distance,
            specialsCount: v.specialsCount,
            address: v.address,

            suburb: v.suburb,
            categories: v.categories,
            priceRange: v.priceRange,
            isInsiderPick: v.isInsiderPick,
            isFavorite: favorites.includes(v.id),
        }));
    }
}

export default new VenueService();
